modified run_config_files_ICA script 2

diff --git a/1-Scripts/run_config_files_ICA b/1-Scripts/run_config_files_ICA
--- a/1-Scripts/run_config_files_ICA
+++ b/1-Scripts/run_config_files_ICA
@@ -1,8 +1,31 @@
 #!/bin/bash
 
-# Specify the directory of your config_files scripts
+# Prompt the user to set the value for the which_computer variable
+echo "Please enter the computer type (e.g., 'local', 'neurospin', 'remote'):"
+read which_computer
+
+# Set the script_dir based on the value of which_computer
+if [ "$which_computer" == "local" ]; then
+    # Specify the directory of your config_files scripts
+    script_dir="/Users/et/Documents/UNICOG/2-Experiments/replayseq/1-Scripts/analysis_scripts/config_files"
+    # Define the BIDS root directory
+    bids_root="/Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS"
+
+elif [ "$which_computer" == "remote" ]; then
+    script_dir=$(dirname "$0")
+    bids_root="/Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS"
+    
+
+elif [ "$which_computer" == "neurospin" ]; then
+    script_dir="$(dirname "$0")/analysis_scripts/config_files"
+    bids_root="$(dirname "$(dirname "$0")")/2-Data/BIDS"
+
+else
+    echo "Invalid input. Please enter 'local', 'remote', or 'neurospin'."
+    exit 1
+fi
+
 #script_dir=$(dirname "$0")
-script_dir="/Users/et/Documents/UNICOG/2-Experiments/replayseq/1-Scripts/analysis_scripts/config_files"
 
 # Function to run a command, check if it was successful, and log the output
 run_command() {
@@ -18,9 +41,6 @@ run_command() {
         echo "$description succeeded." | tee -a "$logfile"
     fi
 }
-
-# Define the BIDS root directory
-bids_root="/Volumes/T5_EVO/1-experiments/REPLAYSEQ/2-Data/BIDS"
 
 # Define the base log directory
 log_base_dir="$bids_root/mne_bids_logs"
